### ISSUE TITLE
Rating 5.5 star

### ISSUE THREAD

**Issue by jv95** [patookllc/patook#5]
Sometimes there is a bug with 5.5 star rating. (only for "our quess") I am using Google Chrome.
![ratingbug](https://cloud.githubusercontent.com/assets/10341166/18221490/3f23e094-717e-11e6-8081-638e927e8ef0.png)

**Comment by patookllc** [comment]
Fixed (I think), can you check now?

**Comment by jv95** [comment]
http://imgur.com/a/CngDS

not fixed.

**Comment by patookllc** [comment]
Is this the user page or photo page? Are they both broken?
