### ISSUE TITLE
Photo report

### ISSUE THREAD

**Issue by jv95** [patookllc/patook#6]
When the picture in gallery is too wide, the report button in the right bottom corner of picture in hidden. 
- Its still there but you have to resize the page to see the whole picture with that report button.
  Position of the report button should be fixed or in the left bottom corner.

**Comment by patookllc** [comment]
Thanks - can you send me a sample link when you get a chance? I haven't seen this on the web yet.

**Comment by patookllc** [comment]
Fixed
